
package pkg2015;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import static pkg2015.Inici.llistaClients;
import projecte.Clients;
import com.thoughtworks.xstream.XStream;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.Writer;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import static pkg2015.Inici.llistaArticles;
import static pkg2015.Inici.llistaProveidors;
import projecte.*;

public class Mostrar extends javax.swing.JFrame {

    public Mostrar() {
        initComponents();
        panel_insert.setVisible(true);
        textArea.setEnabled(false);
        textArea.setDisabledTextColor(Color.BLACK);
    }
    
    String desar;
    String xmlP;
    String xmlC;
    String xmlA;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        xmlClients = new javax.swing.JButton();
        xmlArticles = new javax.swing.JButton();
        xmlProveidors = new javax.swing.JButton();
        Enrera = new javax.swing.JButton();
        Enrera1 = new javax.swing.JButton();
        panel_insert = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        desarBoto = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Projecte Java 2015");
        setMinimumSize(new java.awt.Dimension(1200, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setRequestFocusEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMaximumSize(new java.awt.Dimension(96, 229));
        jPanel2.setMinimumSize(new java.awt.Dimension(96, 229));
        jPanel2.setPreferredSize(new java.awt.Dimension(96, 229));

        xmlClients.setBackground(new java.awt.Color(255, 255, 255));
        xmlClients.setText("Clients");
        xmlClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xmlClientsMouseClicked(evt);
            }
        });
        xmlClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xmlClientsActionPerformed(evt);
            }
        });

        xmlArticles.setBackground(new java.awt.Color(255, 255, 255));
        xmlArticles.setText("Articles");
        xmlArticles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xmlArticlesMouseClicked(evt);
            }
        });
        xmlArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xmlArticlesActionPerformed(evt);
            }
        });

        xmlProveidors.setBackground(new java.awt.Color(255, 255, 255));
        xmlProveidors.setText("Proveidors");
        xmlProveidors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xmlProveidorsMouseClicked(evt);
            }
        });
        xmlProveidors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xmlProveidorsActionPerformed(evt);
            }
        });

        Enrera.setBackground(new java.awt.Color(255, 255, 255));
        Enrera.setText("Enrera");
        Enrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnreraMouseClicked(evt);
            }
        });
        Enrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnreraActionPerformed(evt);
            }
        });

        Enrera1.setBackground(new java.awt.Color(255, 255, 255));
        Enrera1.setText("Sortir");
        Enrera1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Enrera1MouseClicked(evt);
            }
        });
        Enrera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enrera1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xmlClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(xmlArticles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(xmlProveidors, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
            .addComponent(Enrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Enrera1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xmlClients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xmlProveidors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xmlArticles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Enrera)
                .addGap(7, 7, 7)
                .addComponent(Enrera1))
        );

        panel_insert.setMaximumSize(new java.awt.Dimension(800, 600));
        panel_insert.setMinimumSize(new java.awt.Dimension(800, 600));
        panel_insert.setPreferredSize(new java.awt.Dimension(800, 600));
        panel_insert.setVisible(false);

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        desarBoto.setText("Desar...");
        desarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desarBotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_insertLayout = new javax.swing.GroupLayout(panel_insert);
        panel_insert.setLayout(panel_insertLayout);
        panel_insertLayout.setHorizontalGroup(
            panel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(desarBoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_insertLayout.setVerticalGroup(
            panel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_insertLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desarBoto)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void xmlClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xmlClientsMouseClicked

    }//GEN-LAST:event_xmlClientsMouseClicked

    private void xmlArticlesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xmlArticlesMouseClicked
        
    }//GEN-LAST:event_xmlArticlesMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Quan tanquem l'aplicació guardem els clients vàlids al fixer

        //Declarem el client
        ObjectOutputStream sortida = null;
        //Capturem l'excepció i escrivim
        try {
            //Pes escriure des de 0
            sortida = new ObjectOutputStream(new FileOutputStream(Inici.fClients));
            int i;
            for (i = 0; i < Inici.llistaClients.size(); i++) //Escrivim els objectes al fitxer
            {
                sortida.writeObject(Inici.llistaClients.get(i));
            }
        } catch (IOException e) {
            //Mostrem avís
            JOptionPane.showMessageDialog(this, "Error a l'escriure al fitxer:" + e.getMessage());
        } finally {
            if (sortida != null) {
                try {
                    sortida.close();
                } catch (IOException ex) {
                    //Mostremos avís
                    JOptionPane.showMessageDialog(this, "Error al tancar el fitxer:" + ex.getMessage());
                }
            }
        }

    }//GEN-LAST:event_formWindowClosed

     
    private void xmlProveidorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xmlProveidorsMouseClicked
      
    }//GEN-LAST:event_xmlProveidorsMouseClicked

    private void xmlProveidorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmlProveidorsActionPerformed
        XStream xstream = new XStream();
        
        xstream.aliasField("NomComercial", Proveidors.class, "_01nomCom");
        xstream.aliasField("DataAlta", Proveidors.class, "_02dataAlta");
        xstream.aliasField("NomFiscal", Proveidors.class, "_03nomFis");
        xstream.aliasField("CIFNIF", Proveidors.class, "_04cifNif");
        xstream.aliasField("Pais", Proveidors.class, "_05pais");
        xstream.aliasField("Poblacio", Proveidors.class, "_06poblacio");
        xstream.aliasField("Direccio", Proveidors.class, "_07direccio");
        xstream.aliasField("CP", Proveidors.class, "_08cp");
        xstream.aliasField("Telefon", Proveidors.class, "_09tfon");
        xstream.aliasField("Email", Proveidors.class, "_10email");
        xstream.aliasField("Website", Proveidors.class, "_11website");
        xstream.aliasField("CC", Proveidors.class, "_12cc");
        xstream.aliasField("Descompte", Proveidors.class, "_13descompte");
        xstream.aliasField("Notes", Proveidors.class, "_14notes");
        xstream.aliasField("DataEntrega", Proveidors.class, "_15entrega");
        xstream.aliasField("Ports", Proveidors.class, "_16ports");
        xstream.aliasField("Expo", Proveidors.class, "_17expo");
        
        String xmlProveidors = xstream.toXML(llistaProveidors);
        textArea.setText(xmlProveidors);
        xmlP=xmlProveidors;
        
        desar = "proveidors";
    }//GEN-LAST:event_xmlProveidorsActionPerformed

    private void xmlClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmlClientsActionPerformed
        XStream xstream = new XStream();
                
        xstream.aliasField("NomComercial", Clients.class, "_01nomCom");
        xstream.aliasField("DataAlta", Clients.class, "_02dataAlta");
        xstream.aliasField("NomFiscal", Clients.class, "_03nomFis");
        xstream.aliasField("CIFNIF", Clients.class, "_04cifNif");
        xstream.aliasField("Pais", Clients.class, "_05pais");
        xstream.aliasField("Poblacio", Clients.class, "_06poblacio");
        xstream.aliasField("Direccio", Clients.class, "_07direccio");
        xstream.aliasField("CP", Clients.class, "_08cp");
        xstream.aliasField("Telefon", Clients.class, "_09tfon");
        xstream.aliasField("Email", Clients.class, "_10email");
        xstream.aliasField("Website", Clients.class, "_11website");
        xstream.aliasField("CC", Clients.class, "_12cc");
        xstream.aliasField("Notes", Clients.class, "_13notes");
        xstream.aliasField("Descompte", Clients.class, "_14descompte");
        
        
        String xmlClients = xstream.toXML(llistaClients);
        textArea.setText(xmlClients);
        xmlC=xmlClients;
        
        desar = "clients";
    }//GEN-LAST:event_xmlClientsActionPerformed

    private void xmlArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmlArticlesActionPerformed
        XStream xstream = new XStream();
        
        xstream.aliasField("DataAlta", Articles.class, "_01dataAlta");
        xstream.aliasField("Proveidor", Articles.class, "_02proveidor");
        xstream.aliasField("Referencia", Articles.class, "_03ref");
        xstream.aliasField("Nom", Articles.class, "_04nom");
        xstream.aliasField("Descripcio", Articles.class, "_05descripcio");
        xstream.aliasField("Acabat", Articles.class, "_06acabat");
        xstream.aliasField("Altura", Articles.class, "_07alt");
        xstream.aliasField("Amplada", Articles.class, "_08ample");
        xstream.aliasField("Fondaria", Articles.class, "_09fondo");
        xstream.aliasField("PreuProveidor", Articles.class, "_10preuProv");
        xstream.aliasField("PreuVenda", Articles.class, "_11preuVenda");
        
        String xmlArticles = xstream.toXML(llistaArticles);
        textArea.setText(xmlArticles);
        xmlA=xmlArticles;
        
        desar = "articles";
    }//GEN-LAST:event_xmlArticlesActionPerformed

    private void EnreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnreraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EnreraMouseClicked

    private void EnreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnreraActionPerformed
        this.setVisible(false);
        try {
            new Inici().setVisible(true);
        } catch (ThrowPersonal ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EnreraActionPerformed

    private void Enrera1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Enrera1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Enrera1MouseClicked

    private void Enrera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enrera1ActionPerformed
        //En apretar el botó Sortir tanquem el programa en el mètode dispose() que fa que s'execute el mètode formWindowClosed()
        this.dispose();
    }//GEN-LAST:event_Enrera1ActionPerformed

    private void desarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desarBotoActionPerformed
        switch(desar){
/******************************************************************************/
            case "proveidors":
                try{
                    Writer sortida = null;
                    File file = new File("proveidors.xml");
                    sortida = new BufferedWriter(new FileWriter(file));
                    sortida.write(xmlP);
                    sortida.close();
                    System.out.println("Fitxer creat correctament");

                    }catch(Exception e){
                        System.out.println("No s'ha pogut desar el fitxer");
                    }
                break;
/******************************************************************************/
            case "clients":
                try{
                    Writer sortida = null;
                    File file = new File("clients.xml");
                    sortida = new BufferedWriter(new FileWriter(file));
                    sortida.write(xmlC);
                    sortida.close();
                    System.out.println("Fitxer creat correctament");

                    }catch(Exception e){
                        System.out.println("No s'ha pogut desar el fitxer");
                    }
                break;
/******************************************************************************/
            case "articles":
                try{
                    Writer sortida = null;
                    File file = new File("articles.xml");
                    sortida = new BufferedWriter(new FileWriter(file));
                    sortida.write(xmlA);
                    sortida.close();
                    System.out.println("Fitxer creat correctament");

                    }catch(Exception e){
                        System.out.println("No s'ha pogut desar el fitxer");
                    }
                break;
        }
    }//GEN-LAST:event_desarBotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enrera;
    private javax.swing.JButton Enrera1;
    private javax.swing.JButton desarBoto;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_insert;
    private javax.swing.JTextArea textArea;
    private javax.swing.JButton xmlArticles;
    private javax.swing.JButton xmlClients;
    private javax.swing.JButton xmlProveidors;
    // End of variables declaration//GEN-END:variables
}